# .github/workflows/schedule-sql-instances.yml
name: Schedule SQL Instances Management

on:
  schedule:
    - cron: '*/2 * * * *'
    - cron: '*/3 * * * *'


jobs:
  trigger-start-stop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Defina as combinações de ambiente, ação e horários
        include:
          # Parar DEV
          - env: DEV
            instances: 
             - dev-instance-1
             - dev-instance-2     
            action: stop
            cron: '0 20 * * *'
          # Iniciar DEV
          - env: DEV
            instances: [dev-instance-1, dev-instance-2]
            action: start
            cron: '*/3 * * * *'
          # Parar UAT
          - env: UAT
            instances: [uat-instance-1, uat-instance-2]
            action: stop
            cron: '*/2 * * * *'
          
    steps:
      - name: Verificar horário agendado
        if: ${{ github.event.schedule == matrix.cron }}
        run: echo "Executando ação programada para ${{ matrix.env }}"

      - name: Chamar workflow de gerenciamento de instâncias
        if: ${{ github.event.schedule == matrix.cron }}
        uses: .github/workflows/manage-sql-instances.yml
        with:
          instances: ${{ matrix.instances }}
          action: ${{ matrix.action }}
          env: ${{ matrix.env }}