name: test matrix

on:
  workflow_dispatch:

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - env: DEV
            instances: 
              - dev-instance-1
              - dev-instance-2
            action: stop
            cron: '0 20 * * *'
          - env: prod
            instances: 
              - prod-instance-1
              - prod-instance-2
            action: start
            cron: '0 8 * * *'
    steps:
      - name: Exibir informações da matriz
        run: |
          echo "Ambiente: ${{ matrix.env }}"
          echo "Instâncias: ${{ matrix.instances }}"
          echo "Ação: ${{ matrix.action }}"
          echo "Cron: ${{ matrix.cron }}"

      - name: Processar instâncias
        shell: bash
        run: |
          echo "Processando instâncias no ambiente ${{ matrix.env }} com ação ${{ matrix.action }}"

          # Converter o array em uma string JSON
          instances_json='${{ toJson(matrix.instances) }}'

          echo "Conteúdo de instances_json: $instances_json"

          # Converter a string JSON em um array no shell
          instances_array=()
          while IFS= read -r instance; do
            instances_array+=("$instance")
          done < <(echo "$instances_json" | jq -r '.[]')

          # Iterar sobre o array de instâncias
          for instance in "${instances_array[@]}"; do
            echo "Executaria ação '${{ matrix.action }}' na instância: $instance"
            # Comando real aqui
          done