name: test matrix

on:
  workflow_dispatch:

jobs:
  trigger-stop-start:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - env: DEV
            instances: 
             - "dev-instance-1"
             - "dev-instance-2"     
            action: stop
            cron: '0 20 * * *'
          # - env: UAT
          #   instances: ["uat-instance-1", "uat-instance-2"]
          #   action: stop
          #   cron: '*/2 * * * *'
  
    steps:
      - name: Call action
        uses: leonrado/github-actions-test/.github/actions/stop-start-instances@main
        with:
          instances: ${{ toJson(matrix.instances) }}
          action: ${{ matrix.action }}
          env: ${{ matrix.env }}    


